[tool.poetry]
name = "promptolution"
version = "1.0.1"
description = ""
authors = ["Tom Zehle, Moritz Schlager, Timo Heiß"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.26.0"
langchain-anthropic = "^0.1.22"
langchain-openai = "^0.1.21"
langchain-core = "^0.2.29"
langchain-community = "^0.2.12"
pandas = "^2.2.2"
tqdm = "^4.66.5"
scikit-learn = "^1.5.2"

[tool.poetry.group.dev.dependencies]
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
transformers = "^4.44.0"
black = "^24.4.2"
flake8 = "^7.1.0"
isort = "^5.13.2"
pre-commit = "^3.7.1"
ipykernel = "^6.29.5"


[tool.poetry.group.docs.dependencies]
mkdocs = "^1.6.1"
mkdocs-material = "^9.5.39"
mkdocstrings = {version = "^0.26.1", extras = ["python"]}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
line_length = 120
profile = "black"

[tool.pydocstyle]
convention = "google"
